### PR TITLE
Implemented cross-env for Windows compatibility

### PR DESCRIPTION
**Pull request by alfonsograziano**

### CODE REVIEW

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
Can we change the CI workflow so that this also runs on windows?

**Comment by simoneb** [comment]
Oh, are we not testing our own solutions in CI?

**Comment by alfonsograziano** [comment]
> Oh, are we not testing our own solutions in CI?

Not for now, the `verify` script is targeting a specific file that the user is supposed to change (the `index.test.js`) and if I run the verify script before the user works on it, we get an error (because verify is failing)

**Comment by alfonsograziano** [comment]
Not much on one side, we can create another script `verify-solution` that runs the same code of `verify` agains `solution.test.js` instead of the index file. At that point, we can run the `verify-solution` on the CI. On the other side, we need to keep in mind that for some features (see timer/dates mocking) we need Node.js v21, so we will probably play a little bit with the action to make it work correctly

**Comment by simoneb** [comment]
let's do that, we can easily run this on node 21 in CI. if you don't know how, ask

**Pull request merged**
