### PR TITLE
Feat/strip types

### PR DESCRIPTION
**Pull request by pmarchini**
This PR adds a new example related to the [--experimental-strip-types flag](https://nodejs.org/api/cli.html#--experimental-strip-types), along with some new slides.

Minor: The `.nvmrc` file seemed to be invalid, so I updated the required version to support the new experimental flag.

### CODE REVIEW

**Comment by simoneb** [comment]
Shall we really include an experimental feature?

**Comment by pmarchini** [comment]
> Shall we really include an experimental feature?

We already have one: test coverage: [`--experimental-test-coverage`](https://nodejs.org/api/cli.html#--experimental-test-coverage).
After discussing it with @codyzu we thought that this feature, even if experimental, could be an interesting addition to the workshop.

WDYT? 😁

**Comment by simoneb** [comment]
Well the test coverage is experimental but part of the test runner, whereas the types support doesn't have anything to do with the test runner. Not strong opinions though

**Comment by pmarchini** [comment]
The rationale behind adding type stripping is that the workshop also introduces ways to interact with TypeScript codebases, suggesting tools like `tsx` or `ts-node` [(link](https://github.com/nearform/node-test-runner-workshop/tree/master/src/a11-typescript)) 
While this approach works well, it could be helpful to also present users with a "dependency-free" alternative.

We might also consider adding a small slide or note in the section that discusses TypeScript support 😁

**Comment by simoneb** [comment]
I'd prefer to keep experimental features out, until they're not experimental anymore, and unless they're closely related to the test runner.

**Comment by pmarchini** [comment]
Makes perfectly sense ☺️

**Pull request closed without merging**
